name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release version/tag"
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    

      - uses: actions/checkout@v4
        with:
          path: fakeapi

   

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build the Docker image
        working-directory: ${{ github.workspace }}/fakeapi/Pritunl-Fake-API/wydocker
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 -t ${{ env.DOCKER_HUB_USER }}/pritunl:latest -t ${{ env.DOCKER_HUB_USER }}/pritunl:${{ github.event.inputs.version }} .
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}